### ISSUE TITLE
Some scores not combining

### ISSUE THREAD

**Issue by archrhythm** [NetroScript/Jacks-LogsTF-On-Page-Combiner#2]
When combining logs from UGC Ultiduo matches the scores do not combine, the UGC config has round limit 1 by default so teams need to ready up between rounds on the same map, if that makes a difference. It does seem to happen with [twiikuu's combiner](https://ldesgoui.github.io/combine-logs-js/).

Example logs:
http://logs.tf/2606553
http://logs.tf/2606560
becomes: http://logs.tf/2606563
&
http://logs.tf/2598251
http://logs.tf/2598261
becomes: https://logs.tf/2598266

**Comment by NetroScript** [comment]
I took a quick look at it, and considering both twiikuus combiner (which just appends the files to each other) and mine (which also optimized stuff a bit, depending on your settings) don't work I would say the blame is to be on logs.tf.

I also checked and compared the events emitted with ones in working logs (where it does combine the different rounds in the UGC first to 4 format) but didn't really see any difference. So I don't think there would be any trickery to work around it.

I might take another look at it tomorrow, but as of right now there doesn't seem to be anything (easy) I could do. (One could do an edge case detection of 4 players on the server and then fake the score by adding it together in the log combiner with an extra option, but this wouldn't really be any stable or dependable solution)

**Comment by NetroScript** [comment]
I took another look at it, and I don't think there is any warrantable fix. If you look into the logs you showed as an example you see that it detects the multiple rounds of being played, but it doesn't add the scores of the round together. And any trickery which came to my mind would cause the round data to be incorrect. So I will close this and you could maybe try [contacting zooob](https://www.teamfortress.tv/2934), although I don't know if he is still active.
